### ISSUE TITLE
Allow 'import' type exports to be of type '.js' instead of enforcing '.mjs'

### ISSUE THREAD

**Issue by KnisterPeter** [marvinhagemeister/check-export-map#8]
If the `package.json` contains `"type": "module"` the export entry for type `import` may have the `.js` file extension.

Example:

```json
{
  "type": "module",
  "exports": {
    "./file": {
      "import": "./some/file.js"
    }
  }
}
```

@marvinhagemeister 
Is a PR for this welcome?

**Comment by marvinhagemeister** [comment]
sure
